name: Push out directory to repo

on:
  workflow_dispatch:

jobs:
  push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GIT
        run: |
          git config --global user.name WHO53
          git config --global user.email notwho53@gmail.com

      - name: DumperX
        run: |
          git clone https://github.com/DumprX/DumprX ~/D
          cd ~/D
          bash setup.sh
          wget -O rom.zip https://mirrors-obs-2.lolinet.com/firmware/lenowow/2019/Tab_8/TB-8505X/TB-8505X_S100064_200901_BMP.zip
          bash dumper.sh rom.zip
          find ~/D/out -type f -name "*.apk" -delete

      - name: Commit and push changes
        run: |
          git clone https://${{ secrets.PAT }}@github.com/WHO53/rom-lenovo-akita-a9.git ~/a9
          cp -r ~/D/out/* ~/a9
          cd ~/a9
          git add -A
          git commit -m "i"
          git push
