name: Push out directory to repo

on:
  workflow_dispatch:

jobs:
  push-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: GIT
        run: |
          git config --global user.name WHO53
          git config --global user.email notwho53@gmail.com

      - name: DumperX
        run: |
          git clone https://github.com/DumprX/DumprX ~/D
          cd ~/D
          bash setup.sh
          wget -q -O rom.zip https://mirrors.lolinet.com/firmware/lenowow/2023/Tab_M8_4th_Gen_2024/TB301XU/TB301XU_S000083_230830_ROW.zip
          bash dumper.sh rom.zip
          find ~/D/out -type f -name "*.apk" -delete

      - name: Commit and push changes
        run: |
          git clone --depth=1 https://${{ secrets.PAT }}@github.com/WHO53/rom-lenovo-akita-a9.git ~/rom
          cd ~/rom
          mkdir rgx-m8-2024
          mv ~/D/out/vendor/firmware/rgx.fw rgx-m8-2024
          git add -A
          git commit -m "rgx fw dump"
          git push
